appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: af3wUWVR+Igbb8l7UAfPElrL9zOHAijXi+q2YSV3pYPmSS3kps7gsLr8+U6W2plRLIR2/wUk915nBMUNFhS038vUxjjnnT05BUUjKRzNqn1QFSW4inax1gro8dVZj81pDViKHrVej28jjutzAysy/k6UG7LMN8gl4P34vXWnQvYGiDXax8Q6v1EHe6Usd603lkfE1PwbeVVR7c/DeTXqMkk6gSoh5IcL1x2P8fag2+MguFRdw9ovgWXQLCKN4n5U3t73pIs5W0I4ysPSDW7NUHEDq5wCbvkRfOkvBFJPQ9P4x/f1Q/+njv2apvbbxyvZRHPaowFyFnbJqbZu21TfM/fFs5IqNzupx900Qsx/r+YrH3hoa4Vf9Y9Lzs2jf+tUFev57oUBpT7rOxC6+3gmgFyGAWsqTeSYamGpH8bAwTKZ1nWBJxbAb3uMjswGdUOrvJiFpyy1U93dZJj9PnwczQsxrrc2AzvfiQNcSlO8tjk/OYJixziNHogBcTHh5Y1+iF0aZvDN6Ah7XmOUoVcuU3w6yTtZrAUxif+pgJvCotSdZDKcqIfKm3S4HL9I7VXEy/EJJsLAIF1i/Gbl4Gwf7g8561ty0TQbJG+SMfgVKiQrxkSattBTpDOm8towSckOeI5h/cHp77rnGBW8OCPbNa9JTpYkpLjViwJ4y6mCNU0=}
